import 'package:flutter/material.dart';

class IconList {

  static const Map<String, IconData> iconMap = {
    "school": Icons.school_outlined,
    "people": Icons.people_outline,
    "book": Icons.menu_book_outlined,
    "trophy": Icons.emoji_events_outlined,
    "award": Icons.workspace_premium_outlined,
    "target": Icons.track_changes_outlined,
    "star": Icons.star_border,
    "business": Icons.business_center_outlined,
    "laptop": Icons.laptop_outlined,
    "chart": Icons.bar_chart_outlined,
    "menu_book": Icons.book_outlined,
    "bookmark": Icons.bookmark_border,
    "calendar": Icons.calendar_today_outlined,
    "time": Icons.access_time_outlined,
    "alarm": Icons.alarm_outlined,
    "location": Icons.location_on_outlined,
    "bank": Icons.account_balance_outlined,
    "domain": Icons.domain_outlined,
    "heart": Icons.favorite_border,
    "smile": Icons.sentiment_satisfied_outlined,
    "pulse": Icons.monitor_heart_outlined,
    "coffee": Icons.coffee_outlined,
    "restaurant": Icons.restaurant_outlined,
    "music": Icons.music_note_outlined,
    "mic": Icons.mic_none_outlined,
    "video": Icons.videocam_outlined,
    "work": Icons.work_outline,
    "campaign": Icons.campaign_outlined,
    "build": Icons.build_outlined,
    "globe": Icons.public_outlined,
    "flight": Icons.flight_outlined,
    "rocket": Icons.rocket_launch_outlined,
    "shield": Icons.shield_outlined,
    "lock": Icons.lock_outline,
    "key": Icons.key_outlined,
    "idea": Icons.lightbulb_outline,
    "bolt": Icons.bolt_outlined,
    "fire": Icons.local_fire_department_outlined,
    "sports": Icons.sports_soccer_outlined,
    "palette": Icons.palette_outlined,
    "calculator": Icons.calculate_outlined,
    "code": Icons.code_outlined,
    "memory": Icons.memory_outlined,
    "science": Icons.science_outlined,
    "computer": Icons.computer_outlined,
    "phone": Icons.phone_android_outlined,
    "email": Icons.email_outlined,
    "bell": Icons.notifications_none,
  };


  static List<IconData> get iconList => iconMap.values.toList();
}